DELETE http://localhost:5002/api/profile/669fdc85cc4091c3e60b3d0c
Content-Type: application/json

# {
#     "name": "UPDATED test",
#     "email": "test@test.com",
#     "bio": "this is my UPDATED bio",
#     "password": "123!@#Qwe",
#     "plans": ["0"]
# }